export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  ADD_PRODUCT: "ADD_PRODUCT",
  SET_PRODUCTS_DATA: "SET_PRODUCTS_DATA",
  RESET_PRODUCT_DATA: "RESET_PRODUCT_DATA",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  ADD_BASKET_PRODUCT: "ADD_BASKET_PRODUCT",
  SET_BASKET_DATA: "SET_BASKET_DATA",
};
